"""initial schema

Revision ID: 5e9092ece35b
Revises:
Create Date: 2026-07-03 07:37:05.204142+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5e9092ece35b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dns_history",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("resolver", sa.String(length=64), nullable=False),
        sa.Column("response_time_ms", sa.Float(), nullable=True),
        sa.Column("is_timeout", sa.Boolean(), nullable=False),
        sa.Column("is_error", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dns_history")),
    )
    op.create_index(
        "ix_dns_history_domain_timestamp", "dns_history", ["domain", "timestamp"], unique=False
    )
    op.create_table(
        "http_history",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("dns_time_ms", sa.Float(), nullable=True),
        sa.Column("tcp_connect_time_ms", sa.Float(), nullable=True),
        sa.Column("tls_handshake_time_ms", sa.Float(), nullable=True),
        sa.Column("ttfb_ms", sa.Float(), nullable=True),
        sa.Column("total_time_ms", sa.Float(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_http_history")),
    )
    op.create_index(
        "ix_http_history_url_timestamp", "http_history", ["url", "timestamp"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column(
            "incident_type",
            sa.Enum(
                "internet_slow",
                "packet_loss",
                "dns_failure",
                "internet_down",
                "gateway_down",
                name="incidenttype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "started",
                "active",
                "recovered",
                name="incidentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "excellent",
                "good",
                "warning",
                "high",
                "critical",
                "offline",
                name="severity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "triggering_monitor",
            sa.Enum(
                "ping",
                "dns",
                "http",
                "speedtest",
                "traceroute",
                "tcpdump",
                name="monitortype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_table(
        "ping_history",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("is_timeout", sa.Boolean(), nullable=False),
        sa.Column("jitter_ms", sa.Float(), nullable=True),
        sa.Column("rolling_avg_ms", sa.Float(), nullable=True),
        sa.Column("packet_loss_pct", sa.Float(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "excellent",
                "good",
                "warning",
                "high",
                "critical",
                "offline",
                name="severity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ping_history")),
    )
    op.create_index(
        "ix_ping_history_target_timestamp", "ping_history", ["target", "timestamp"], unique=False
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_settings_key")),
    )
    op.create_table(
        "speed_test_history",
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("download_mbps", sa.Float(), nullable=True),
        sa.Column("upload_mbps", sa.Float(), nullable=True),
        sa.Column("ping_ms", sa.Float(), nullable=True),
        sa.Column("server_name", sa.String(length=255), nullable=True),
        sa.Column("server_id", sa.String(length=64), nullable=True),
        sa.Column("is_error", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_speed_test_history")),
    )
    op.create_index(
        "ix_speed_test_history_timestamp", "speed_test_history", ["timestamp"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "telegram",
                "discord",
                "email",
                "webhook",
                name="alertchannel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.String(length=2000), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", name="alertstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_alerts_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_table(
        "tcp_captures",
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("interface", sa.String(length=64), nullable=False),
        sa.Column("file_path", sa.String(length=1000), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "recording",
                "completed",
                "failed",
                name="capturestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_tcp_captures_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tcp_captures")),
    )
    op.create_table(
        "traceroute_results",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("target", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("hop_number", sa.Integer(), nullable=False),
        sa.Column("hop_ip", sa.String(length=45), nullable=True),
        sa.Column("hop_hostname", sa.String(length=255), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("is_timeout", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_traceroute_results_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traceroute_results")),
    )
    op.create_index(
        "ix_traceroute_results_run_id_hop",
        "traceroute_results",
        ["run_id", "hop_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_traceroute_results_run_id_hop", table_name="traceroute_results")
    op.drop_table("traceroute_results")
    op.drop_table("tcp_captures")
    op.drop_table("alerts")
    op.drop_index("ix_speed_test_history_timestamp", table_name="speed_test_history")
    op.drop_table("speed_test_history")
    op.drop_table("settings")
    op.drop_index("ix_ping_history_target_timestamp", table_name="ping_history")
    op.drop_table("ping_history")
    op.drop_table("incidents")
    op.drop_index("ix_http_history_url_timestamp", table_name="http_history")
    op.drop_table("http_history")
    op.drop_index("ix_dns_history_domain_timestamp", table_name="dns_history")
    op.drop_table("dns_history")
    # ### end Alembic commands ###
